#!/bin/bash
KEYCLOAK_URL=$1
KEYCLOAK_ADMIN_PASSWORD=$2
REALM=$3
REALM_URL=$4
REALM_SECRET=$5
USER_FIRSTNAME=$6
USER_LASTNAME=$7
USER_PASSWORD=$8
USER_EMAIL=$9
ADMIN_EMAIL=${10}

CLIENT=${REALM}
./add-realm.sh $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM
./add-client.sh $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM $CLIENT ${REALM_SECRET} ${REALM_URL} 
./add-role.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM realm admin
./add-user.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM user1 ${USER_EMAIL} ${USER_FIRSTNAME} ${USER_LASTNAME} ${USER_PASSWORD} users user
./add-user.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM admin ${ADMIN_EMAIL} ${USER_FIRSTNAME} ${USER_LASTNAME} admin1 admins  admin
./create-keycloak-json.sh $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM $REALM $REALM_URL
