#!/bin/bash
KEYCLOAK_URL=$1
KEYCLOAK_ADMIN_PASSWORD=$2
REALM=$3
REALM_URL=$4
REALM_SECRET=$5
USER_FIRSTNAME=$6
USER_LASTNAME=$7
USER_PASSWORD=$8
USER_EMAIL=$9
ADMIN_EMAIL=${10}
SERVICE_PASSWORD=${11}

CLIENT=${REALM}
./add-realm.sh $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM
./add-client.sh $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM $CLIENT ${REALM_SECRET} ${REALM_URL} 
./add-role.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM realm admin
./add-user-id.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM user1 ${USER_EMAIL} ${USER_FIRSTNAME} ${USER_LASTNAME} ${USER_PASSWORD} users user e2ab55fa-e65d-4502-9bb1-ef9856d09dde
./add-user-id.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM user2 second.${USER_EMAIL} ${USER_FIRSTNAME} ${USER_LASTNAME}2 ${USER_PASSWORD} users user e2ab55fa-e65d-4502-9bb1-ef9856d09ddf
./add-user-id.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM user3 third.${USER_EMAIL}  ${USER_FIRSTNAME} ${USER_LASTNAME}3 ${USER_PASSWORD} users user e2ab55fa-e65d-4502-9bb1-ef9856d09def
./add-user-id.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM user4 fourth.${USER_EMAIL} ${USER_FIRSTNAME} ${USER_LASTNAME}4 ${USER_PASSWORD} users user e2ab55fa-e65d-4502-9bb1-ef9856d09dff
./add-user-id.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM admin ${ADMIN_EMAIL} ${USER_FIRSTNAME} ${USER_LASTNAME} admin1 admins  admin d0fc69dd-11a5-4a0c-bbb0-7436dbd9f53e
./add-user-id.sh  $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM service service.${ADMIN_EMAIL} Service User "${SERVICE_PASSWORD}"  admins  admin d0fc69dd-11a5-4a0c-bbb0-7436dbd9f53f
./create-keycloak-json.sh $KEYCLOAK_URL $KEYCLOAK_ADMIN_PASSWORD $REALM $REALM $REALM_URL

