keyckoak:
    image: gennyproject/keycloak:7.1.0
    links:
        - db:db
    environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=xxxxxxxxx
        - DB_VENDOR=mysql
        - DB_ADDR=db
        - DB_PORT=3306
        - DB_DATABASE=keycloakdb
        - DB_USER=genny
        - DB_PASSWORD=password
        - PROXY_ADDRESS_FORWARDING=true
    ports:
        - "9980:8080"
        - "9990:9990"
    volumes:
        # all customized themes mounted to themes-repo(don't overwrite base, keycloak, keyckoak-preview themes)
        # then copy customized themes from themes-repo to /opt/jboss/keycloak/themes 
        - ./keycloak-themes/themes:/opt/jboss/keycloak/themes-repo

db:
    image: mysql:8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: keycloakdb 
        MYSQL_USER: genny
        MYSQL_PASSWORD: password
    volumes:
        - ./mysqldata:/var/lib/mysql
    ports:
        - "3318:3306"
